
title: Denis Mistrik
logo: "/images/websitelogo.png?raw=true" 
description: >
  Computer Science Master's + Bachelor's graduate from the University of Southern California
  <br><br>
  Working at USC Multi-omics Mass Spectrometry Core
  <br><br>
  Interests include Finance, Video Game Design, AI, Robotics, Databases, and DevOps 
  <br><br>
  mistrik[at]usc.edu | mistrikdenis[at]gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/denis-mistrik/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://denismistrikusc.github.io/resume.pdf">View My Resume</a> 
  <br><br>

remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-themeW

nav:
  - text: "Home"
    url: /
  - text: "Resume"
    url: /resume.pdf
